# Specify a base image
FROM node:alpine

#Install some dependencies

WORKDIR /purchify/client
COPY package*.json ./
RUN npm install
COPY . .

# Set up a default command
EXPOSE 3000
CMD [ "npm","start" ]