FROM node:16-alpine
WORKDIR /client
ENV PATH="/.node_modules/.bin:$PATH"
COPY . .
RUN npm install
RUN npm run build
CMD ["npm", "start"]

## docker build -t purchify-test -f Dockerfile.test .
## docker run -p 3000:3000 purchify-test
## docker compose build 
## docker compose up